version: '3'
services:
   postgres:
      image: 'postgres:latest'
   redis:
      image: 'redis:latest'

   nginx:
      depends_on:
         - api
         - client
      restart: always #to make sure nginx is ready to go,
      build: 
         dockerfile: Dockerfile.dev
         context: ./nginx
      ports:
         - '3050:80'
      
   api:      #initialy is server. reference on nginx default.conf
      build:
        dockerfile: Dockerfile.dev
        context: ./server #use all the files here to build the image.
      volumes:
        - /app/node_modules #inside dont try to ovewrite this folder, 
        - ./server:/app  # look into server diretory and copy everything
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
   client:
      environment:
         - WDS_SOCKET_PORT=0
      build: 
         dockerfile: Dockerfile.dev
         context: ./client
      volumes:
         - /app/node_modules
         - ./client:/app
   worker:
      build: 
         dockerfile: Dockerfile.dev
         context: ./worker
      volumes:
         - /app/node_modules
         - ./worker:/app
      environment:
         - REDIS_HOST=redis
         - REDIS_PORT=6379



